name: simple_lint_rules
description: A simple lint rule set and analysis options configuration.
version: 2.0.1
repository: https://pub.dev/packages/simple_lint_rules

# Property to support tooling around auto-publishing.
auto_publish: true

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  lints: ^2.0.0
