name: simple_lint_rules
description: A simple lint rule set and analysis options configuration.
version: 2.0.2+2
repository: https://pub.dev/packages/simple_lint_rules

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  lints: ^2.0.0
