# A CI configuration to auto-publish pub packages.
#
# To use this script, make sure the repo is configured to squash PR commits.

name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  auto-publish:
    # Update this to the host GitHub org.
    if: github.repository_owner == 'devoncarew'

    # This is required for authentication using OIDC.
    permissions:
      id-token: write 

    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of the repo. This fetches all commits in order to
      # determine the changed files.
      - name: Check out repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          fetch-depth: 0

      - name: Set up Dart
        uses: dart-lang/setup-dart@main

      - name: Install Firehose
        run: dart pub global activate firehose

      - name: Run pub get
        run: dart pub get

      - name: Verify changed packages (publish dry-run)
        if: ${{ github.event_name == 'pull_request' }}
        run: dart pub global run firehose --verify
        env:
          PR_LABELS: "${{ join(github.event.pull_request.labels.*.name) }}"

      - name: Publish changed packages
        if: ${{ github.event_name == 'push' }}
        run: dart pub global run firehose --publish
