# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [ main ]
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:
  publish:
    if: github.repository_owner == 'devoncarew'
    uses: devoncarew/firehose/.github/workflows/publish.yml@main
